server:
  port: 8083


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.231.61.133/healthTrackDatabase?useSSL=false&allowPublicKeyRetrieval=true
    username: shexpi8fmal
    password: henaogbu99da
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: 129.226.155.208
    username: asufhiwegn5
    password: fioha7kasw
    port: 5672
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=100,maximumSize=500,expireAfterAccess=1800s
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: healthtrack.server.web@gmail.com
    password: duar jakv bsyp hrgf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  type-handlers-package: com.healthtrack.calculator.config.mybatis

logging:
  level:
    org.springframework.security: DEBUG

